# Generated by Django 4.1.4 on 2023-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0006_remove_booking_booking_date_remove_booking_plane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
